### ISSUE TITLE
React 18 issues

### ISSUE THREAD

**Issue by Kestutis** [bbbtech/storybook-formik#58]
Hi, I'm getting into errors with docs page and formik decorator. Already described my issue here - https://github.com/storybookjs/storybook/issues/17831#issuecomment-1180633872

I managed to find, that while I'm not using `@bbbtech/storybook-formik` and using `<Formik>` instead, then everything is fine.
I can see from devDependecies in this project, that is required React 16 or React 17. Any plans to support React 18?

**Comment by bhishp** [comment]
Apologies, I have just picked up this issue, I'll try and get some time soon to test out with R18. As always, happy to accept PRs on this too

**Comment by jshin8** [comment]
Any updates on supporting React 18?

**Comment by Crownpack07** [comment]
Any progress on this front?

**Comment by bhishp** [comment]
I'm afraid that I'm not really actively maintaining this project anymore so I encourage PRs to contribute and fill gaps like the above 🙏🏽

**Comment by Crownpack07** [comment]
I am trying to create a PR for the upgrade, but I do not have permissions to push up a branch to make the PR

**Comment by bhishp** [comment]
Have merged your fix @Crownpack07, please test v3.0.0 in your projects and reply here if you encounter any compatibility issues, thanks.
